### ISSUE TITLE
[Bug report] Failed to parse dynamic list

### ISSUE THREAD

**Issue by shan-shaji** [fluttercandies/FlutterJsonBeanFactory#132]
### Version

4.5.0

### Platforms

Android, iOS

### Device Model

Android 11

### flutter info

```sh
[✓] Flutter (Channel stable, 2.10.5, on macOS 13.0 22A380 darwin-arm, locale
    en-IN)
    • Flutter version 2.10.5 at /Users/jisjoe/fvm/versions/2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (11 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/jisjoe/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### How to reproduce?

  final List<dynamic>? value = jsonConvert.convertListNotNull<dynamic>(json['data']);

Here when passing a dynamic list `json['data']` the data is not parsing and is thrown with an error.

### Logs

```sh
I/flutter ( 8952): asT<dynamic> UnimplementedError: dynamic unimplemented #0      JsonConvert._asT (package:example/generated/json/base/json_convert_content.dart:395:9)
I/flutter ( 8952): #1      JsonConvert.convertList.<anonymous closure> (package:example/generated/json/base/json_convert_content.dart:346:39)
I/flutter ( 8952): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
I/flutter ( 8952): #3      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
I/flutter ( 8952): #4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:206:27)
I/flutter ( 8952): #5      new _GrowableList.of (dart:core-patch/growable_array.dart:153:28)
I/flutter ( 8952): #6      new List.of (dart:core-patch/array_patch.dart:51:28)
I/flutter ( 8952): #7      ListIterable.toList (dart:_internal/iterable.dart:213:44)
I/flutter ( 8952): #8      JsonConvert.convertList (package:example/generated/json/base/json_convert_content.dart:346:76)
I/flutter ( 8952): #9      $MemberBorrowingPlanFromJson (package:example/generated/json/member_entity.g.dart:345:58)
I/flutter ( 8952): #10     new MemberBorrowingPlan.fromJson (package:example/models/member_entity.dart:154:69)
I/flutter ( 8952): #11     JsonConvert._asT (package:example/generated/json/base/json_convert_content.dart:393:37)
I/flutter ( 8952): #12     JsonConvert.convert (package:example/generated/json/base/json_convert_content.dart:334:14)
I/flutter ( 8952): #13     $MemberFromJson (package:example/generated/json/member_entity.g.dart:182:58)
I/flutter ( 8952): #14     new Member.fromJson (package:example/models/member_entity.dart:22:56)
I/flutter ( 8952): #15     JsonConvert._asT (package:example/generated/json/base/json_convert_content.dart:393:37)
I/flutter ( 8952): #16     JsonConvert.convert (package:example/generated/json/base/json_convert_content.dart:334:14)
I/flutter ( 8952): #17     $MemberEntityFromJson (package:example/generated/json/member_entity.g.dart:6:38)
I/flutter ( 8952): #18     new MemberEntity.fromJson (package:example/models/member_entity.dart:10:62)
I/flutter ( 8952): #19     MemberRepository.fetchMember (package:example/repositories/member_repository.dart:33:42)
I/flutter ( 8952): <asynchronous suspension>
I/flutter ( 8952): #20     AppBloc._fetchUser (package:example/blocs/app/app_bloc.dart:264:35)
I/flutter ( 8952): <asynchronous suspension>
I/flutter ( 8952): #21     AppBloc._onAppAuthenticated (package:example/blocs/app/app_bloc.dart:220:5)
I/flutter ( 8952): <asynchronous suspension>
I/flutter ( 8952): #22     Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:226:13)
I/flutter ( 8952): <asynchronous suspension>
```

**Comment by zhangruiyu** [comment]
You need to provide json and an entity class
