### ISSUE TITLE
[Bug report] 插件泛型转换判断类型使用了T.toString()，在web端release 模式报错

### ISSUE THREAD

**Issue by Josin22** [fluttercandies/FlutterJsonBeanFactory#141]
### Version

4.5.0

### Platforms

Web

### Device Model

chrome or any browser

### flutter info

```sh
C:\Users\chrys>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.4)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2022.2)
[√] Connected device (5 available)
[√] Network resources

! Doctor found issues in 2 categories.
```

### How to reproduce?

使用插件，web端打包release模式， 在泛型转换是报错

### Logs

```sh
asT<minified:c0<minified:mu>> UnimplementedError: minified:c0<minified:mu> unimplemented UnimplementedError: minified:c0<minified:mu> unimplemented
js_primitives.dart:42     at Object.f (http://localhost:64383/main.dart.js:3157:3)
js_primitives.dart:42     at aFu.Xh (http://localhost:64383/main.dart.js:113134:48)
js_primitives.dart:42     at aFu.p (http://localhost:64383/main.dart.js:113109:12)
js_primitives.dart:42     at aOx.atk (http://localhost:64383/main.dart.js:115192:29)
js_primitives.dart:42     at http://localhost:64383/main.dart.js:115157:5
js_primitives.dart:42     at b8O.a (http://localhost:64383/main.dart.js:4466:62)
js_primitives.dart:42     at b8O.$2 (http://localhost:64383/main.dart.js:48119:14)
js_primitives.dart:42     at b7u.$1 (http://localhost:64383/main.dart.js:48113:21)
js_primitives.dart:42     at b3H.aPB (http://localhost:64383/main.dart.js:49137:34)
js_primitives.dart:42     at b3H.TE (http://localhost:64383/main.dart.js:49139:21)
js_primitives.dart:42 Another exception was thrown: Instance of 'minified:lX<void>'
```

**Comment by zhangruiyu** [comment]
不能够啊 web我还测试过的

**Comment by Gdchh** [comment]
还是会

<img width="891" height="238" alt="Image" src="https://github.com/user-attachments/assets/3616aee4-039d-4e22-b2c7-b0315604c5c8" />

**Comment by zhangruiyu** [comment]
我直接这么打的 flutter build web  --release 是可以的
